### PR TITLE
Fixes typo in the README (#2)

### LINKED ISSUE #2: Wrong link name
The link to the ST 2120-1 document says ST 2121-1. Change to ST 2120-1 to avoid confusion.

### PR DESCRIPTION
**Pull request by billredmann**
"2121-1" -> "2120-1" in two places.  (Fixes #2)

### CODE REVIEW

**Review by palemieux — APPROVED** [review]

**Comment by billredmann** [comment]
Pierre - I'd like to link Paul's issue #2 to this pull request, so that it's closed by this, but I'm not seeing any control (e.g., in the right column by "Linked issues") to permit that.  Do I not have the right permissions? or is there something else needed?

--- update - it looks as if I should have used the phrase "Fixes #2" in the commit message.  Looking to see how to edit that.

--- update - got it.  done.

**Review by billredmann — COMMENTED** [review]
Add notation that this Fixes #2. - DONE

**Comment by billredmann** [comment]
Now correctly linked to resolve issue #2.

**Comment by billredmann** [comment]
Ready to merge.

**Comment by palemieux** [comment]
@billredmann You, as the editor, should merge. Please use a descriptive commit message, e.g. `Fixes typo in the README (#2)`

**Review by billredmann — COMMENTED** [review]
Fixes typo in README (#2)

**Comment by billredmann** [comment]
@palemieux - I'm not being offered a merge button.

Also, there was a race condition where you'd reviewed the change and a half minute later, I'd requested you to review the change, so it seems there's an outstanding review request.  Is that the reason?

**Pull request merged**
